POSITIVE_EMAIL = 'test_nskryukov@mail.ru'
POSITIVE_PASSWORD = 'secretpool'
NEGATIVE_EMAIL_FIRST = 'abcabc'
NEGATIVE_EMAIL_SECOND = 'mymail'
NEGATIVE_PASSWORD_FIRST = 'abcabc'
NEGATIVE_PASSWORD_SECOND = 'takethispassword'
