name: Auto assign
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  add-reviewrs-and-assignrees:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: '.github/auto-assign-persons.yml'