name: MySQL Homework
on:
  push:
    branches:
      - 'homework6'
  workflow_dispatch:
jobs:
  MySQLHomework:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/homework6'
    timeout-minutes: 5
    env:
      MYSQL_ROOT_PASSWORD: pass
    steps:
      - uses: actions/checkout@v2
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: $MYSQL_ROOT_PASSWORD
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=$MYSQL_ROOT_PASSWORD --silent; do
            sleep 1
          done
      - name: Test with pytest
        run: |
          pytest ${{ steps.extract_branch.outputs.branch }} -n 2