name: Selenium Homework
on:
  pull_request_target:
    types: [opened, edited, reopened, ready_for_review, review_requested]
  workflow_dispatch:
jobs:
  SeleniumHomework:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.6"
      - name: Information about directory
        run: |
          echo "PWD: $(pwd)"
          ls -al
      - name: Install chromedriver locally
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '105.0.5195.19'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test homework1 with pytest
        if: ${{ github.ref_name == 'homework1' }}
        timeout-minutes: 3
        run: |
          pytest ${{ steps.extract_branch.outputs.branch }} --headless
      - name: Test homework2 with pytest and pytest-xdist
        if: ${{ github.ref_name == 'homework2' }}
        timeout-minutes: 8
        run: |
          pytest ${{ steps.extract_branch.outputs.branch }} -n2 --headless
