name: Pylint for code
on:
  push:
    branches:
      - '!main'
      - 'homework*'
jobs:
  PyLint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Use pylint
      run: |
        pylint ${{ steps.extract_branch.outputs.branch }} --exit-zero